### ISSUE TITLE
"AI: Diagnostic message: backoff logic was enabled" -  Why? What to do?

### ISSUE THREAD

**Issue by ardacetinkaya** [microsoft/ApplicationInsights-dotnet#2170]
Hi all;

Our application is running as an Azure App Service within ASE. The application's runtime is .NET Framework 4.7 and uses connection string, not instrumentation key to have Application Insights connectivity.

After some time in Application Insights's search results we can not see any log about the application, just some trace messages;

> AI: Diagnostic message: backoff logic was disabled, transmission will be resolved.
> AI: Diagnostic message: backoff logic was enabled. Backoff internal exceed 60 min. Last status code received from the backend was 999

This continue for a while in every hour without any application logs. I don't get why, but sometimes logs are reflected to Application Insights as expected.

From the messages I understand that this is related with exponential backoff approach. I have just checked the repo and see that 999 is for "unknown network error" 

I also could not find any troubleshoot document about it, any idea or helps are welcome :)

**Comment by TimothyMothra** [comment]
Hello,
This sounds like a problem with the Ingestion service.
Please open a support ticket for this here:  [Azure Support Center](https://azure.microsoft.com/support/create-ticket/).

**Comment by alrod** [comment]
@ardacetinkaya, what was the issue? Thanks in advance.

**Comment by javiercoulon** [comment]
Hi, wondering if there is any official root cause on this. We have been noticing this kind of items lately and the logs are not being registered.

**Comment by ardacetinkaya** [comment]
It was told that this is because of some internal regional problems and then it is resolved by that time.(In that time also some resources were newly available in there)

**Comment by ask3101** [comment]
I am still seeing similar issue on the recent SDKs as well. Is there any fix provided for this issue.

**Comment by TimothyMothra** [comment]
@ask3101 the conditions that cause "backoff" are typically unique per customer. 
These can be affected by either your network or our regional datacenters. 

If you're seeing this infrequently, it shouldn't be a cause for concern. 
The SDK has mechanisms to retry telemetry. 

If you're seeing this frequently and experiencing data loss, please open a support ticket so someone can look into this with you.

**Comment by ask3101** [comment]
Thanks for the response.  I tried raising the support ticket and reviewed with support team over call. We were asked to verify the firewalls on the servers. The TELNET to the provided domains failed, but we are able to see the logs with 2- 4 days of delay.  If there is a firewalls issue, we should be able to see the logs at all. All we wanted is to retain the real time logging feature that was working earlier.
